### ISSUE TITLE
question about message: key already exists

### ISSUE THREAD

**Issue by ghost** [arundurvasula/angsd-wrapper#52]
I have a regions file that looks like this:
9:52173261-52173990
5:12995975-12997206
9:113061855-113063368
9:15043238-15044776
2:14957924-14959456

After running ANGSD_Theta.sh I got a message: Problem with chr: 9, key already exists. 9:113061855-113063368 is not being written either. Is that because this region has less than 10 reads?

**Comment by noahrose** [comment]
I'm having this same error message using angsd to generate saf files across specific regions, what does the error message mean? I also tried to use the -sites option, but angsd gave an error saying that the .idx and .bin files were older than the sites file, even though they were not and had in fact been created in the same script. Right now I am unable to generate saf files in specific regions via either option, any help would be much appreciated!

**Comment by arundurvasula** [comment]
Hi Noah,

I couldn't find this comment on Github, so I'm copying your email as well.

Which version of ANGSD-wrapper/ANGSD are you using? This issue is on a
deprecated version and we're now using this repository:
https://github.com/mojaveazure/angsd-wrapper

Another thing that might affect this is that ANGSD likes your sites to be
in the same order as your reference fasta. In the example in the error
message, 9 is out of order. If the sites you are providing are also out of
order, you may get this message.

Hope that helps!

On Sun, Jun 5, 2016 at 7:58 PM, Noah Rose <notifications@github.com> wrote:

> I'm having this same error message using angsd to generate saf files
> across specific regions, what does the error message mean? I also tried to
> use the -sites option, but angsd gave an error saying that the .idx and
> .bin files were older than the sites file, even though they were not and
> had in fact been created in the same script. Right now I am unable to
> generate saf files in specific regions via either option, any help would be
> much appreciated!
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/arundurvasula/angsd-wrapper/issues/52#issuecomment-223827299>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACmsxqb3tGvr0LzBYV_ctocL7cBsSixeks5qIw4xgaJpZM4DEAQZ>
> .
>



-- 
Arun Durvasula
arun.durvasula@gmail.com

**Comment by noahrose** [comment]
Hi Arun,

Sorry about that, I deleted the comment after I did a clean pull and
compile from the master branch and everything seemed to be working better
--I think you're exactly right that I was just a couple commits behind, I
don't think the out of order problem was the issue in this case. Thanks so
much!

Noah

**Comment by arundurvasula** [comment]
Ah okay, no worries. Glad it works now! Let me know if you run into any other issues!
