### ISSUE TITLE
GFF in zoomed plot

### ISSUE THREAD

**Issue by dmvelasco** [arundurvasula/angsd-wrapper#73]
This is a 3 Mb region in peach that appears to have too many gene tracks in the plot (top) for the region size. Is it possible that the GFF is not zooming to the selected region?
![pp_5_z_sub](https://cloud.githubusercontent.com/assets/2659412/7716203/44a3f026-fe44-11e4-862e-40f5e6ff4d88.png)

**Comment by arundurvasula** [comment]
Yep, it's possible! Could you link me to your GFF and possibly send over the data so that I can play around with it?

**Comment by dmvelasco** [comment]
GFF3 is at ftp://ftp.bioinfo.wsu.edu/species/Prunus_persica/Prunus_persica-genome.v1.0/genes/Prunus_persica_v1.0_genes.gff3.gz
Try accessing .pestPG files from FARM directory (sending path)

**Comment by arundurvasula** [comment]
Okay after looking into this, it looks like an issue with coordinates. The code for GFF just graphs whatever is marked as a gene, without regard for the first column (chromosome). For the example, the GFF has only information for chromosome 10, which is good because that's what we're graphing in the thetas graph.

In your case, however, the GFF contains 9 different scaffolds and it graphs all of them, overlaying on each other. For now, is it possible for you to grab only the GFF info for whatever chromosome you're looking at (5 in the example above)?

I will work on a fix that subsets the GFF data to make sure the annotations are only from the chromosome you're looking at.

Hope that helps!
